require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/frosty_quests", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FrostyQuest. As you add validations to FrostyQuest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FrostyQuest.create! valid_attributes
      get frosty_quests_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      frosty_quest = FrostyQuest.create! valid_attributes
      get frosty_quest_url(frosty_quest)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_frosty_quest_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      frosty_quest = FrostyQuest.create! valid_attributes
      get edit_frosty_quest_url(frosty_quest)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FrostyQuest" do
        expect {
          post frosty_quests_url, params: { frosty_quest: valid_attributes }
        }.to change(FrostyQuest, :count).by(1)
      end

      it "redirects to the created frosty_quest" do
        post frosty_quests_url, params: { frosty_quest: valid_attributes }
        expect(response).to redirect_to(frosty_quest_url(FrostyQuest.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FrostyQuest" do
        expect {
          post frosty_quests_url, params: { frosty_quest: invalid_attributes }
        }.to change(FrostyQuest, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post frosty_quests_url, params: { frosty_quest: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested frosty_quest" do
        frosty_quest = FrostyQuest.create! valid_attributes
        patch frosty_quest_url(frosty_quest), params: { frosty_quest: new_attributes }
        frosty_quest.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the frosty_quest" do
        frosty_quest = FrostyQuest.create! valid_attributes
        patch frosty_quest_url(frosty_quest), params: { frosty_quest: new_attributes }
        frosty_quest.reload
        expect(response).to redirect_to(frosty_quest_url(frosty_quest))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        frosty_quest = FrostyQuest.create! valid_attributes
        patch frosty_quest_url(frosty_quest), params: { frosty_quest: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested frosty_quest" do
      frosty_quest = FrostyQuest.create! valid_attributes
      expect {
        delete frosty_quest_url(frosty_quest)
      }.to change(FrostyQuest, :count).by(-1)
    end

    it "redirects to the frosty_quests list" do
      frosty_quest = FrostyQuest.create! valid_attributes
      delete frosty_quest_url(frosty_quest)
      expect(response).to redirect_to(frosty_quests_url)
    end
  end
end
